### PR TITLE
running skip/dryRun mode invokes update(contexts, out)

### PR DESCRIPTION
**Pull request by oriy**

### CODE REVIEW

**Comment by oriy** [comment]
@liorhar @AvihayTsayeg please review

**Comment by liorhar** [comment]
good job, if you really want to be helpful I believe the best option is to get rid of this stupid groovy wrapper. so no hacks are needed on external repo.

**Comment by oriy** [comment]
@liorhar please merge
... I don't mess with bald guys ...

**Comment by oriy** [comment]
@liorhar I just understood what you meant, this wrapper is no longer needed,
 I started upgrading the https://github.com/kenshoo/groovy-liquibase which can be used directly

**Comment by liorhar** [comment]
right, but even that project isn't needed, since we migrated to good? old xml these plugins are just cumbersome wrappers around the well published docs.

**Comment by oriy** [comment]
the custom groovy changesets code are still needed, do you mean we should just migrate this code into search repo? or continue using liquibase-dsl just directly from db.gradle?

**Comment by lielran** [comment]
Lets wrap the wrapper

**Comment by oriy** [comment]
I don't follow

**Comment by liorhar** [comment]
both options are better than today, the best option is to change existing liqui changeset into xml there aren't much of them. if that's technically impossible, e.g. checksums are changed then I'd meld the plugin code into the search repo (db module) so it's easier to modify and all in one place.

**Pull request merged**
